language: objective-c
osx_image: xcode9.2

env:
- PROJECT=HorizontalPickerDemo.xcodeproj DESTINATION="OS=10.0,name=iPhone 6s" SDK=iphonesimulator11.2 SCHEME=HorizontalPicker RUN_TESTS="YES"
- PROJECT=HorizontalPickerDemo.xcodeproj DESTINATION="OS=10.1,name=iPhone 7"  SDK=iphonesimulator11.2 SCHEME=HorizontalPicker RUN_TESTS="YES"
- PROJECT=HorizontalPickerDemo.xcodeproj DESTINATION="OS=11.1,name=iPhone 7"  SDK=iphonesimulator11.2 SCHEME=HorizontalPicker RUN_TESTS="YES"
- PROJECT=HorizontalPickerDemo.xcodeproj DESTINATION="OS=11.2,name=iPhone 8"  SDK=iphonesimulator11.2 SCHEME=HorizontalPicker RUN_TESTS="YES"

notifications:
  slack:
    on_success: always
    on_failure: change
    rooms:
      secure: b/iKKSvXRK+ihrGjbeww9vX321IkbZVeRWTG2UlTsEs36oL/e1ge7bH57jPBhEhtLgHkXutq2ZGwz67YxgYj6dc5Hx+NfISdyrJIqVmt+5T7Yyv/yI7uTa/g9WP/RalkYXMbUdtEtjlCQcXntdzGBsbDvn2nxpX4cqYowA4golo=

script:
- set -o pipefail

- if [ $RUN_TESTS == "YES" ]; then
      xcodebuild analyze test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -verbose | xcpretty -c;
  else
      xcodebuild build analyze -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -verbose | xcpretty -c;
  fi

# Build for reporting test coverage
- if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -project HorizontalPickerDemo.xcodeproj -scheme HorizontalPickerDemo -destination "platform=iOS Simulator,name=iPhone 7" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
  fi

after_success:
  - bash <(curl -s https://codecov.io/bash)